version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./data:/data
    container_name: timl-beibootserver
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: timl-beibootclient
